import { BiAbacus, BiCategory } from 'react-icons/bi'
import {
  BsCart2,
  BsClockHistory,
  BsEye,
  BsEyeSlash,
  BsFillXCircleFill,
  BsQuestionSquare,
  BsShieldCheck,
  BsShieldExclamation,
  BsSignpost,
  BsSortDown,
  BsTranslate,
} from 'react-icons/bs'
import { FiEdit, FiLogIn, FiLogOut, FiMinus, FiPlus } from 'react-icons/fi'
import { HiOutlineUser, HiOutlineUsers } from 'react-icons/hi'
import { IoImagesOutline, IoSearch } from 'react-icons/io5'
import { TfiLayoutSlider } from 'react-icons/tfi'
import { VscLocation, VscThreeBars } from 'react-icons/vsc'

import {
  RiArrowDownSFill,
  RiArrowDropDownLine,
  RiArrowDropLeftLine,
  RiArrowDropRightLine,
  RiArrowDropUpLine,
  RiArrowRightLine,
  RiChat1Line,
  RiCheckboxCircleLine,
  RiCloseLine,
  RiDeleteBinLine,
  RiHandbagLine,
  RiHeartLine,
  RiHome6Line,
  RiInstagramFill,
  RiLinkedinFill,
  RiMore2Fill,
  RiPencilRuler2Line,
  RiPhoneFill,
  RiSave2Line,
  RiStarFill,
  RiTimeFill,
  RiTwitterFill,
  RiUserLocationFill,
  RiUserLocationLine,
  RiWallet3Line,
  RiYoutubeFill,
} from 'react-icons/ri'

import { CgSandClock } from 'react-icons/cg'

const Icons = {
  ArrowDown: RiArrowDownSFill,
  ArrowDown: RiArrowDropDownLine,
  ArrowLeft: RiArrowDropLeftLine,
  ArrowRight: RiArrowRightLine,
  ArrowRight2: RiArrowDropRightLine,
  ArrowUp: RiArrowDropUpLine,
  Bag: RiHandbagLine,
  Bars: VscThreeBars,
  Cart: BsCart2,
  Category: BiCategory,
  Check: RiCheckboxCircleLine,
  Clock: BsClockHistory,
  Clock2: CgSandClock,
  Close: RiCloseLine,
  Comment: RiChat1Line,
  Cross: BsFillXCircleFill,
  Delete: RiDeleteBinLine,
  Edit: FiEdit,
  Exclamation: BsShieldExclamation,
  Eye: BsEye,
  EyeSlash: BsEyeSlash,
  Filter: BiAbacus,
  Heart: RiHeartLine,
  Home: RiHome6Line,
  Image: IoImagesOutline,
  Instagram: RiInstagramFill,
  Linkedin: RiLinkedinFill,
  Location: RiUserLocationLine,
  Location2: VscLocation,
  Login: FiLogIn,
  Logout: FiLogOut,
  Minus: FiMinus,
  More: RiMore2Fill,
  Phone: RiPhoneFill,
  Plus: FiPlus,
  Post: BsSignpost,
  Question: BsQuestionSquare,
  Rule: RiPencilRuler2Line,
  Save: RiSave2Line,
  Search: IoSearch,
  ShieldCheck: BsShieldCheck,
  Slider: TfiLayoutSlider,
  Sort: BsSortDown,
  Star: RiStarFill,
  Times: RiTimeFill,
  Translate: BsTranslate,
  Twitter: RiTwitterFill,
  User: HiOutlineUser,
  UserLocation: RiUserLocationFill,
  Users: HiOutlineUsers,
  Wallet: RiWallet3Line,
  Youtube: RiYoutubeFill,
}

export default Icons
